name: Rust
on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"
  CC: clang
  CXX: clang++

jobs:
  build:
    runs-on: gha-arm
    timeout-minutes: 30
    steps:
      - run: which rustc
      - run: rustc --version
      - run: md5sum /home/runner/.cargo/bin/rustc
      - run: rustc --version
      - run: rustc --version
      - run: rustc --version
      - run: rustc --version
      - run: rustc --version
